jwt:
  secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

oauth:
  kakao:
    client-id: 218218ad0178d4a0b76a55ffeb155957
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect: http://localhost:8080/api/auth/kakao/logout
      logout: https://kapi.kakao.com/v1/user/logout
  naver:
    secret: RktX7yIc6P
    client-id: Sz6qeDvQKMAa96LN6ESa
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/loginTest
      driver-class-name: org.h2.Driver
      username: sa
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: hikari
      password: 1


  h2:
    console:
      path: /h2console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true